/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onepacket;

import java.awt.EventQueue;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;

/**
 *
 * @author Robotics
 */
public class MainFrame extends javax.swing.JFrame {

    private void error(final String s) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                jLabel2.setText(s);
            }
        });
    }

    private void output(final String s) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTextPane1.setText(s);
            }
        });
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Thread t;
        final byte[] buf = new byte[65536];
        t = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        DatagramSocket dg = new DatagramSocket(1140);
                        error("all fine");
                        DatagramPacket p = new DatagramPacket(buf, buf.length);
                        try {
                            while (true) {
                                dg.receive(p);
                                output(new String(p.getData(), 0, p.getLength()));
                            }
                        } catch (IOException ex) {
                            error("rec failure");
                        }
                    } catch (SocketException e) {
                        error("could not make socket " + String.valueOf(System.currentTimeMillis()));
                    }
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                    }
                }
            }
        });
        t.setDaemon(true);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));

        jTextPane1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Listens to UDP 1140");
        jPanel1.add(jLabel1);
        jPanel1.add(filler1);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("All fine");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
